[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
base = "https://mainnet.base.org"
base_goerli = "https://goerli.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }
